import Head from "next/head";
import Header from "./header";
import Footer from "./footer";
import Home1 from "./home1";
import About from "./about";
import Skill from "./skill";

import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
export default function Home() {
  return (
    <div >
      <Head>
        <title>test1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/styles/output.css" rel="stylesheet"></link>
     
      </Head>
      
     
      <Home1/>
      
      


      
    </div>
  );
}
